#!/usr/bin/env python3

import re
import os
import xml.etree.ElementTree as ET
import random


def read_beast_xml_alignments(xml_file):
    tree = ET.parse(xml_file)
    root = tree.getroot()

    # Find all sequence elements
    sequences = {}
    for seq in root.iter('sequence'):
        # Get taxona ID and sequence data
        taxon = seq.find('taxon')
        taxon_id = taxon.get('idref') if taxon is not None else seq.get('taxon')
        seq_data = taxon.tail.strip()

        sequences[taxon_id] = seq_data

    return sequences

header = \
'''<?xml version="1.0" standalone="yes"?>

<!-- Generated by BEAUTi v1.10.4 Prerelease #bc6cbd9                         -->
<!--       by Alexei J. Drummond, Andrew Rambaut and Marc A. Suchard         -->
<!--       Department of Computer Science, University of Auckland and        -->
<!--       Institute of Evolutionary Biology, University of Edinburgh        -->
<!--       David Geffen School of Medicine, University of California, Los Angeles-->
<!--       http://beast.community/                                           -->
<beast version="1.10.4">
	

	<!-- The list of taxa to be analysed (can also include dates/ages).          -->
	<!-- ntax=8                                                                  -->
	<taxa id="taxa">
		<taxon id="human"/>
		<taxon id="chimpanzee"/>
		<taxon id="gorilla"/>
		<taxon id="orangutan"/>
		<taxon id="macaca"/>
		<taxon id="howler_monkey"/>
		<taxon id="bushbaby"/>
		<taxon id="flying_lemur"/>
	</taxa>
'''

footer = '''
	<convert id="codonAlignment" dataType="codon" geneticCode="universal">
        <alignment idref="alignment"/>
    </convert>


	<!-- The unique patterns from 1 to end                                       -->
	<!-- npatterns=816                                                           -->
	<patterns id="patterns" from="1" strip="false">
		<alignment idref="codonAlignment"/>
	</patterns>



	<newick id="startingTree">
	(((((((human:0.01, chimpanzee:0.01):0.01, gorilla:0.02):0.01, orangutan:0.03):0.01, macaca:0.04):0.01, howler_monkey:0.05):0.01, bushbaby:0.06):0.01, flying_lemur:0.07);
	</newick>

	<!-- Generate a tree model                                                   -->
	<treeModel id="treeModel">
		<coalescentTree idref="startingTree"/>
		<rootHeight>
			<parameter id="treeModel.rootHeight"/>
		</rootHeight>
		<nodeHeights internalNodes="true">
			<parameter id="treeModel.internalNodeHeights"/>
		</nodeHeights>
		<nodeHeights internalNodes="true" rootNode="true">
			<parameter id="treeModel.allInternalNodeHeights"/>
		</nodeHeights>
	</treeModel>


	<!-- Statistic for sum of the branch lengths of the tree (tree length)       -->
	<treeLengthStatistic id="treeLength">
		<treeModel idref="treeModel"/>
	</treeLengthStatistic>

	<!-- Statistic for time of most recent common ancestor of tree               -->
	<tmrcaStatistic id="age(root)" absolute="true">
		<treeModel idref="treeModel"/>
	</tmrcaStatistic>

    <!-- Frequence Model -->
	<frequencyModel id="freqModel" dataType="codon-universal" codonFromNucleotide="true">
		<alignment idref="alignment"/>
		<!-- <alignment idref="codonAlignment"/> -->
		<frequencies>
			<parameter id="nucleotidefrequencies" dimension="4"/>
		</frequencies>
     </frequencyModel>

   <!-- Codon Model -->
    <yangCodonModel id="yg" geneticCode="universal">
        <omega>
            <parameter id="omega" value="0.1" lower="0"/>
        </omega>
        <kappa>
            <parameter id="kappa" value="1.5" lower="0"/>
        </kappa>
        <frequencyModel idref="freqModel"/>
    </yangCodonModel> 

	<arbitraryBranchRates id="sbranchSpecific.omegas" centerAtOne="false" randomizeRates="false">
		<treeModel idref="treeModel"/>
		<rates>
			<parameter id="omega.rates" value="1.0" lower="0"/>
        </rates>
	</arbitraryBranchRates>

	<bayesianBridgeDistribution id="bbDistribution">
		<slabWidth>
			<parameter id="slabWidth" value="2.0"/>
		</slabWidth>
	 	<globalScale>
	 		<parameter id="globalScale" value="1" lower="0"/>
	 	</globalScale>
 		<exponent>
 			<parameter id="exponent" value="0.1"/>
 		</exponent>
		<localScale>
			<parameter id="localScale" value="1" lower="0.0" dimension="14"/>
		</localScale>
	</bayesianBridgeDistribution>

	<autoCorrelatedRatesPrior id="substBranchRatesPrior.omegas" scaling="none" log="true" operateOnIncrements="true">
		<arbitraryBranchRates idref="sbranchSpecific.omegas"/>
 		<bayesianBridgeDistribution idref="bbDistribution"/>
 	</autoCorrelatedRatesPrior>

	<fixedEffects id="fixedEffectsModel.omegas" timeEffect="false">
		<treeModel idref="treeModel"/>
		<parameter id="omega.location" lower="0.0" value="1E-1"/>
	</fixedEffects>
	
	<locationScaledBranchRateModel id="scaled.omegas">
		<treeModel idref="treeModel"/>
		<arbitraryBranchRates idref="sbranchSpecific.omegas"/>
		<fixedEffects idref="fixedEffectsModel.omegas"/>
	</locationScaledBranchRateModel>

    <branchSpecificSubstitutionParameterBranchModel id="branchSpecificParameters">
    	<substitutionModel idref="yg"/>
    	<treeModel idref="treeModel"/>
    	<substitutionParameters>
	    	<parameter idref="omega"/>
    	</substitutionParameters>
    	<branchRateModels>
    		<locationScaledBranchRateModel idref="scaled.omegas"/>
    	</branchRateModels>
    </branchSpecificSubstitutionParameterBranchModel>

    <siteModel id="siteModel">
        <substitutionModel>
            <yangCodonModel idref="yg"/>
        </substitutionModel>
        <gammaShape gammaCategories="4">
            <parameter id="siteModel.alpha" value="1.25" lower="0.0"/>
        </gammaShape>
    </siteModel>

    <arbitraryBranchRates id="branchRates" reciprocal="false" exp="false" centerAtOne="false">
        <rates>
            <parameter id="branchRates.rates" value="1" lower="0"/>
        </rates>
        <treeModel idref="treeModel"/>
    </arbitraryBranchRates>


	<!-- Likelihood for tree given sequence data                                 -->
	<treeDataLikelihood id="treeLikelihood" useAmbiguities="true" usePreOrder="true"  scalingScheme="always" delayScaling="false" branchRateDerivative="true"
	branchInfinitesimalDerivative="true">
		<patterns idref="patterns"/>
		<siteModel idref="siteModel"/>
		<treeModel idref="treeModel"/>
		<arbitraryBranchRates idref="branchRates"/>
		<branchSpecificSubstitutionParameterBranchModel idref="branchSpecificParameters"/>
	</treeDataLikelihood>

	<report>
		<treeDataLikelihood idref="treeLikelihood"/>
	</report>

	<branchSubstitutionParameterGradient id="omega.gradient" traitName="SubstitutionParameterGradient.omega" useHessian="false" dim="0">
	    <treeDataLikelihood idref="treeLikelihood"/>
		<branchSpecificSubstitutionParameterBranchModel idref="branchSpecificParameters"/>
		<locationScaledBranchRateModel idref="scaled.omegas"/>
    </branchSubstitutionParameterGradient>

	<gradientWrtIncrements id="incrementGradient.omega">
		<autoCorrelatedRatesPrior idref="substBranchRatesPrior.omegas"/>
	</gradientWrtIncrements>

	<branchRateGradientWrtIncrements id="branchRateGradientWrtIncrements.omegas">
		<branchSubstitutionParameterGradient idref="omega.gradient"/>
		<gradientWrtIncrements idref="incrementGradient.omega"/>
	</branchRateGradientWrtIncrements>

	<jointGradient id="jointIncrementGradient.omega">
		<branchRateGradientWrtIncrements idref="branchRateGradientWrtIncrements.omegas"/>
		<gradientWrtIncrements idref="incrementGradient.omega"/>
	</jointGradient>	

	<operators id="operators" optimizationSchedule="log">

        <hamiltonianMonteCarloOperator weight="10" nSteps="6" stepSize="1E-1" mode="vanilla"
        	drawVariance="1.0" autoOptimize="true" targetAcceptanceProbability="0.8"
        	preconditioning="adaptiveDiagonal" preconditioningUpdateFrequency="10" preconditioningDelay="20000000"
        	gradientCheckCount="0" gradientCheckTolerance="0">
        	<jointGradient idref="jointIncrementGradient.omega"/>

 		</hamiltonianMonteCarloOperator>

	</operators>

	<!-- Define MCMC                                                             -->
	<mcmc id="mcmc" chainLength="0" autoOptimize="true" fullEvaluation="0" autoOptimizeDelay="0" smoothAcceptanceRatio="true">
		<posterior id="posterior">
			<prior id="prior">
				<dirichletPrior alpha="1.0" sumsTo="1.0">
					<parameter idref="nucleotidefrequencies"/>
				</dirichletPrior>
				<exponentialPrior mean="0.5" offset="0.0">
					<parameter idref="siteModel.alpha"/>
				</exponentialPrior>
				<exponentialPrior offset="0" mean="1">
                    <parameter idref="kappa"/>
                </exponentialPrior>
				<autoCorrelatedRatesPrior idref="substBranchRatesPrior.omegas"/>
				<exponentialPrior mean="2.0" offset="0.0">
					<parameter idref="omega.location"/>
				</exponentialPrior>

			</prior>
			<likelihood id="likelihood">
				<treeDataLikelihood idref="treeLikelihood"/>
			</likelihood>
		</posterior>
		<operators idref="operators"/>

		<!-- write log to screen                                                     -->
		<log id="screenLog" logEvery="20">
			<column label="Posterior" dp="4" width="12">
				<posterior idref="posterior"/>
			</column>


			<column label="rootHeight" sf="6" width="12">
				<parameter idref="treeModel.rootHeight"/>
			</column>

			<column label="age(root)" sf="6" width="12">
				<tmrcaStatistic idref="age(root)"/>
			</column>

		</log>

	</mcmc>

'''

analytic_tail = \
'''
    <maximizeWrtParameter id="maximizeWrtParameter" startAtCurrentState = "true" printToScreen="true">
        <branchRateGradientWrtIncrements idref="branchRateGradientWrtIncrements.omegas"/>
    </maximizeWrtParameter>

    <report>
		<maximizeWrtParameter idref="maximizeWrtParameter"/>
    </report>

    <report fileName="BRCA1_analytic_MLE_logLikelihood.txt">
		<treeDataLikelihood idref="treeLikelihood"/>
    </report>


</beast>
'''

numeric_tail = \
'''

    <maximizeWrtParameter id="maximizeWrtParameter" startAtCurrentState = "true" printToScreen="true">
        <densityWrtParameter id="densityWrtParameter">
			<parameter idref ="omega.rates"/>
            <treeDataLikelihood idref="treeLikelihood"/>
        </densityWrtParameter>
		<signTransform>
			<parameter idref ="omega.rates"/>
		</signTransform>

    </maximizeWrtParameter>

    <report>
		<maximizeWrtParameter idref="maximizeWrtParameter"/>
    </report>

    <report fileName="BRCA1_numeric_MLE_logLikelihood.txt">
		<treeDataLikelihood idref="treeLikelihood"/>
    </report>


</beast>
'''

if __name__ == "__main__":
    numeric_lnL_name = "BRCA1_numeric_MLE_logLikelihood.txt"
    analytic_lnL_name = "BRCA1_analytic_MLE_logLikelihood.txt"
    xml_template_name = "BRCA1_shrinkage_fixedRates_MLE.xml"

    analytic_printScreen = "BRCA1_analytic_printScreen.txt"
    numeric_printScreen = "BRCA1_numeric_printScreen.txt"

    original_sequences = read_beast_xml_alignments(xml_template_name)

    seq_lengths = set(len(original_sequences[taxon]) for taxon in original_sequences)
    assert(len(seq_lengths) == 1)
    alignment_length = list(seq_lengths)[0]
    assert(alignment_length % 3 == 0)
    alignment_length = int(alignment_length / 3)

    if not os.path.isdir('./xmls'):
        os.mkdir('./xmls')
    if not os.path.isdir('./logs'):
        os.mkdir('./logs')

    failed = []
    for seed_num in range(1, 101):
        seed_numeric_xml_file = "./xmls/seed_" + str(seed_num) + "_MLE_numeric.xml"
        numeric_lnL_file_name = "./logs/seed_" + str(seed_num) + "_numeric_MLE_logLikelihood.txt"

        random.seed(seed_num)
        sample_with_replacement_idx = random.choices(range(alignment_length), k=alignment_length)
        seed_analytic_xml_file = "./xmls/seed_" + str(seed_num) + "_MLE_analytic.xml"
        analytic_lnL_file_name = "./logs/seed_" + str(seed_num) + "_analytic_MLE_logLikelihood.txt"

        analytic_printScreen_file_name = "./logs/seed_" + str(seed_num) + "_MLE_analytic_printScreen.txt"
        numeric_printScreen_file_name = "./logs/seed_" + str(seed_num) + "_MLE_numeric_printScreen.txt"
        with open(seed_analytic_xml_file, "w+") as f:
            f.write(header)
            f.write('\t<alignment id="alignment" dataType="nucleotide">\n')
            for taxon in original_sequences:
                f.write("\t\t<sequence>\n")
                f.write('\t\t\t<taxon idref="' + taxon + '"/>\n')
                f.write('\t\t\t' + "".join([original_sequences[taxon][(3 * idx) : (3 * idx + 3)] for idx in sample_with_replacement_idx]) + "\n")
                f.write('\t\t</sequence>\n')
            f.write('\t</alignment>\n')

            f.write(footer)
            f.write(analytic_tail)

        beast_analytic_cmd = ["/usr/bin/java", "-jar", "-Djava.library.path=/usr/local/lib",
                              "/Users/xiangji/GitFolders/beast-mcmc/build/dist/beast.jar",
                              "-load_state BRCA1_hmc_save -force_resume", "-overwrite", seed_analytic_xml_file , ">", analytic_printScreen]



        with open(seed_numeric_xml_file, "w+") as f:
            f.write(header)
            f.write('\t<alignment id="alignment" dataType="nucleotide">\n')
            for taxon in original_sequences:
                f.write("\t\t<sequence>\n")
                f.write('\t\t\t<taxon idref="' + taxon + '"/>\n')
                f.write('\t\t\t' + "".join([original_sequences[taxon][(3 * idx) : (3 * idx + 3)] for idx in sample_with_replacement_idx]) + "\n")
                f.write('\t\t</sequence>\n')
            f.write('\t</alignment>\n')

            f.write(footer)
            f.write(numeric_tail)

        beast_numeric_cmd = ["/usr/bin/java", "-jar", "-Djava.library.path=/usr/local/lib",
                              "/Users/xiangji/GitFolders/beast-mcmc/build/dist/beast.jar",
                              "-load_state BRCA1_hmc_save -force_resume", "-overwrite", seed_numeric_xml_file , ">", numeric_printScreen]

        try:
            if not os.path.isfile(analytic_lnL_file_name):
                os.system(" ".join(beast_analytic_cmd))
                os.rename(analytic_lnL_name, analytic_lnL_file_name)
                os.rename(analytic_printScreen, analytic_printScreen_file_name)

            if not os.path.isfile(numeric_lnL_file_name):
                os.system(" ".join(beast_numeric_cmd))
                os.rename(numeric_lnL_name, numeric_lnL_file_name)
                os.rename(numeric_printScreen, numeric_printScreen_file_name)

        except:
            failed.append(seed_num)


    failed_analytic = []
    failed_numeric = []
    diff_results = []
    for seed_num in range(1, 101):
        analytic_lnL_file_name = "./logs/seed_" + str(seed_num) + "_analytic_MLE_logLikelihood.txt"
        numeric_lnL_file_name = "./logs/seed_" + str(seed_num) + "_numeric_MLE_logLikelihood.txt"

        if not os.path.isfile(analytic_lnL_file_name):
            failed_analytic.append(seed_num)
            analytic_lnL = None
        else:
            with open(analytic_lnL_file_name, "r") as f:
                result = f.readline()
                analytic_lnL = -float(re.search(r"[0-9]*\.?[0-9]+", result).group(0))

        if not os.path.isfile(numeric_lnL_file_name):
            failed_numeric.append(seed_num)
            numeric_lnL = None
        else:
            with open(numeric_lnL_file_name, "r") as f:
                result = f.readline()
                numeric_lnL = -float(re.search(r"[0-9]*\.?[0-9]+", result).group(0))

        if analytic_lnL != None and numeric_lnL != None:
            diff = analytic_lnL - numeric_lnL
            diff_results.append(diff)











